### ISSUE TITLE
oni-lda-c:  indexing calculation for aggregation of gammas is off

### ISSUE THREAD

**Issue by NathanSegerlind** [Open-Network-Insight/open-network-insight#21] opened 2016-04-12 16:28 UTC
In some situations, the aggregation of the gammas will hang because the aggregation logic has an "off" calculation.

lda-estimate.c,  lines approx. 338-370

**Comment by grantbabb** [comment] 2016-04-24 21:55
Resolved with PR 6 in oni-lda-c
Tested successfully on customer deployment

Root cause: apparently for an even number of worker processes and small amount of data, an extra loop gets added to the gamma consolidation loop.  The more robust fix was to use a mod approach for filtering out documents that had been processed locally.

**Closed by grantbabb** 2016-04-24 21:55 UTC
